### ISSUE TITLE
not working with latest version of java or burp suite

### ISSUE THREAD

**Issue by RAVIPRAJ** [iamaldi/rapid#6]
it is not working with latest version of burp suite it is need to upgrade with new version of burp suite

**Comment by iamaldi** [comment]
@RAVIPRAJ Thanks for raising the issue, will take a look and let you know once a patch is available.

**Comment by iamaldi** [comment]
@RAVIPRAJ I have confirmed that with the latest version of Burp Suite Community Edition (v2021.6.2) Rapid is working without any errors.

Burp Suite groups all extension's menu items under the `Extensions` menu entry. Please check if this is the case.
![image](https://user-images.githubusercontent.com/22844526/125109678-56513b80-e0ec-11eb-9182-236a8235cb81.png)

Otherwise, if this issue persists, it would be helpful if you could provide the errors you encounter while using Rapid.

Best regards,
A.
